apiVersion: v1
kind: Pod
metadata:
  name: memory-stress
spec:
  containers:
    - name: stress
      image: polinux/stress-ng
      command: ["stress-ng"]
      # 模拟消耗 10G 内存（根据你 Node 的实际配置调整）
      # --vm 1 表示启动一个工作进程, --vm-bytes 指定大小
      args: ["--vm", "1", "--vm-bytes", "2.5G", "--vm-keep"]
  # 建议加上节点选择器，避免把主节点搞死
  nodeSelector:
    kubernetes.io/hostname: aks-work-32123589-vmss000000
