apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: master-k8s-api-dev
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - master-k8s
  selector:
    matchLabels:
      app: events-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
