apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kickoffqi/master-k8s
    targetRevision: dev
    path: infra/argocd/addons/argo-rollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

  # CRDs are frequently mutated by the Kubernetes apiserver (defaulting, ordering, status),
  # which can cause persistent OutOfSync. Ignore those diffs.
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .status
        - .metadata.annotations
        - .spec.conversion

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
