apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-readonly
subjects:
  - kind: ServiceAccount
    name: ops-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ops-readonly
