apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master-k8s-kustomize-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=ghcr.io/kickoffqi/master-k8s-api,frontend=ghcr.io/kickoffqi/master-k8s-frontend
    argocd-image-updater.argoproj.io/api.allow-tags: regexp:^sha-[0-9a-f]+$
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^sha-[0-9a-f]+$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomize
spec:
  project: default
  source:
    repoURL: https://github.com/kickoffqi/master-k8s
    targetRevision: main
    path: infra/kustomize/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: master-k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
